# Generated by Django 4.2.1 on 2023-05-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_itemmenu_active_itemmenu_description_itemmenu_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmenu',
            name='eng',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
