# Generated by Django 4.2.1 on 2023-05-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_agate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agate',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
