# Generated by Django 4.2.1 on 2023-05-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_itemmenu_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmenu',
            name='category',
        ),
        migrations.AddField(
            model_name='itemmenu',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='menucategory', to='blog.category'),
        ),
    ]
