# Generated by Django 4.2.1 on 2023-05-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_itemmenu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='engid',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
