# Generated by Django 4.2.1 on 2023-05-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_category_engid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmenu',
            name='eng',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='itemmenu',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemmenu',
            name='title',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
